YOLOV3:
  CFG: "./detector/YOLOv3/cfg/yolo_v3.cfg"
  WEIGHT: "./detector/YOLOv3/weight/darknet53_weights_pytorch.pth"
  CLASS_NAMES: "./detector/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.4
  NMS_THRESH: 0.3
